### PR TITLE
add `--watch` flag to `build` script of each package

### PR DESCRIPTION
**Pull request by Aa-thomas**
Adding the `--watch` flag will cause the package to be rebuilt whenever there is a change detected, that way we don't need to remember to manuallly rebuild whenever we make changes.

### CODE REVIEW

**Comment by mitchellbutler** [comment]
Hey @Aa-thomas, this approach causes the build to fail since the build pipeline expects the process to end. I think you could tweak this, though, to work with the `yarn dev` command in the root of the monorepo by moving your changes to a new script called `dev` (example below). I've also added the change of removing ` --minify` flag from the `dev` version since it takes more time and makes things less debuggable, also since bundle sizes aren't as important in dev.

```
  "scripts": {
    "lint": "TIMING=1 eslint \"**/*.ts*\"",
    "build": "tsup ./index.tsx --format cjs --minify --dts --clean",
    "dev": "tsup ./index.tsx --format cjs --dts --clean --watch"
  },
```

Let me know if this helps.

**Review by mitchellbutler — CHANGES_REQUESTED** [review]
See my comment in the conversation tab.

**Comment by Aa-thomas** [comment]
I see what you mean, I'll move it to a separate dev script

**Review by mitchellbutler — APPROVED** [review]
👍

**Pull request merged**
